### ISSUE TITLE
om nom code ?

### ISSUE THREAD

**Issue by woeterman94** [windyboy1704/CutTheRopeTimeTravel#1]
What is the omnom code? And why do I have to enter it?
![image](https://user-images.githubusercontent.com/5755057/58942656-77613880-877e-11e9-947f-d22deb0a5538.png)

**Comment by yell0wsuit** [comment]
1. Did you read the sentence under the typing box?
2. This game originally created for a Burger King event, back in 2013. They distributed the code for any participants to play it. I forgot to upload the non-code version (don't know if I do, too lazy and too busy for another project right now), at that time only this version was available because this code-asking script was deeply integrated to the game's base code. I could not remove it (doing so would break the whole script) so I decided to make a workaround.
